yolo_model:

  config_file:
    name: hive-yolov3-set-1.cfg
  weight_file:
    name: yolov3_july_21_set_1.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - pistol
      - smartphone
      - knife
      - monedero
      - billete
      - tarjeta
      - person
