yolo_model:

  config_file:
    name: yolov3-tiny-hive-23-july-set-1.cfg
  weight_file:
    name: yolov3-tiny_4800.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - pistol
      - smartphone
      - knife
      - monedero
      - billete
      - tarjeta
      - person