yolo_model:

  config_file:
    name: yolov3-tiny-hive-23-july-set-1.cfg
  weight_file:
    name: v3_tiny_13_july_21/yolov3-tiny_4800.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - bed
      - chair
      - sofa
      - table
      - broom
      - person
      - file_cabinet
      - bookshelf
      - cabinet
      - cart
      - desk
      - stretcher