yolo_model:

  config_file:
    name: yolov3-tiny-hive.cfg
  weight_file:
    name: v3_tiny_12_july_21.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - bed
      - chair
      - sofa
      - table
      - broom
      - person
      - file_cabinet
      - bookshelf
      - cabinet
      - cart
      - desk
      - stretcher